### ISSUE TITLE
Loosen dependency versions?

### ISSUE THREAD

**Issue by RevCBH** [bananaml/banana-python-sdk#5]
I'm running into a conflict with `banana-dev` depending on `requests==2.26.0`. I need `requests>=2.27.0` and was wondering if the was a reason for such a narrow constraint.

**Comment by tonyf** [comment]
+1 to this. The specified version of `urllib` is below the minimum required for `sentry-sdk`

**Comment by lingster** [comment]
+1 to this, I am trying to integrete sentry with banana-dev, but banana-dev is pinned to urllib3==1.26.7, whereas sentry-srk is looking for urllib3 >= 1.26.11

**Comment by erik-dunteman** [comment]
Hey! I'll take this on, will test with most recent requests version and peg the version as a range between the two. Will report back.

**Comment by erik-dunteman** [comment]
requests has a SemVer policy thankfully so we can follow that
https://requests.readthedocs.io/en/latest/community/release-process/

will make urlLib min 1.26.11 and let requests dictate exactly which

**Comment by erik-dunteman** [comment]
I've loosened requirements to `requests>=2.26.0,<3.0.0` which allows for urllib3 version `1.26.13`, and have verified that the latest `sentry-sdk==1.12.1` successfully installs with`urllib3>=1.26.11` requirement met.

Changes can be viewed here
https://github.com/bananaml/banana-python-sdk/pull/6

I'll be pushing this momentarily as `banana-dev==4.0.1` to pypi, so feel free to upgrade your install with `pip3 install banana-dev==4.0.1`

**Comment by erik-dunteman** [comment]
Confirming this is deployed as version 4.0.1 :)

Same tests pass on live version.

**Comment by erik-dunteman** [comment]
@RevCBH @tonyf @lingster thanks for raising the issue and the patience on the fix here. Cheers! Let me know if any other issues arise.
